"""Add association proxy to Company and Dev

Revision ID: 0448c541a1e9
Revises: 1d52d7f0e183
Create Date: 2023-04-04 15:25:16.295647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0448c541a1e9'
down_revision = '1d52d7f0e183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
