"""Add relationship to company

Revision ID: 1d52d7f0e183
Revises: 5b5d92fb0afe
Create Date: 2023-04-04 15:09:03.612335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d52d7f0e183'
down_revision = '5b5d92fb0afe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
