"""Update company relationship

Revision ID: 29012a467c77
Revises: fc6ebf80a624
Create Date: 2023-04-03 15:58:23.337581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29012a467c77'
down_revision = 'fc6ebf80a624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
