"""Update relationships

Revision ID: 4903a38e7cd8
Revises: 24ba6e5723a5
Create Date: 2023-04-04 08:32:39.887171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4903a38e7cd8'
down_revision = '24ba6e5723a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
