"""Add association proxy to Company and Dev

Revision ID: 5180069b8289
Revises: 0448c541a1e9
Create Date: 2023-04-04 15:27:19.346430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5180069b8289'
down_revision = '0448c541a1e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
