"""Update relationships, revert relationships to freebie only

Revision ID: 5b5d92fb0afe
Revises: 74be8320efca
Create Date: 2023-04-04 08:35:49.142364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5d92fb0afe'
down_revision = '74be8320efca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
